spring:
  #  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hnswez66
    url: jdbc:mysql://8.140.245.208 :3306/cjQimo?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

#      mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: none